---
# Variables used:
# registry_image
# APP_VERSION
# active_profiles
# env
# ucp_username
# network_pcops
# traefik_ntwk

version: "3.5"
services:
  pco-staff-scheduler-ui:
    image: ${registry_image}:${APP_VERSION}
    # compose env variables
    environment:
      - SPRING_PROFILES_ACTIVE=${active_profiles}
      - CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_LABEL=${env}
      - ENV_NAME=${env}
      - SPRING_APPLICATION_NAME=pco-staff-scheduler-ui
      - PCO_LOG_MODE=console
      - PCO_STATIC_CONTENT_SERVER_OPTS='${jvm_options}'
    networks:
      - pcops-ntwk
    healthcheck:
      test: ["CMD-SHELL", "(curl -f http://localhost:8081/padmin/health && exit 0) || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 2
      labels:
        # UCP Access Labels
        - 'com.docker.ucp.access.owner=${ucp_username}'
        - 'com.docker.ucp.access.label=/Shared/pcops'
        - 'traefik.docker.network=${traefik_ntwk}'
        - 'com.docker.lb.network=${traefik_ntwk}'
        - 'traefik.sso.frontend.rule=Host:pco-gateway-qa.premierinc.com;PathPrefix=/pcops/staff-scheduler-ui'
        - 'traefik.sso.frontend.priority=200'
        - 'traefik.sso.port=8080'
        - 'traefik.sso.enable=true'
        - 'traefik.nsso.frontend.rule=Host:pco-gateway-qa-inside.premierinc.com;PathPrefix=/pcops/staff-scheduler-ui'
        - 'traefik.nsso.frontend.priority=200'
        - 'traefik.nsso.port=8080'
        - 'traefik.nsso.enable=true'
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == worker]
networks:
  pcops-ntwk:
    external: true
    name: "${network_pcops}"
