{{- if ge (len (.Files.Glob "secrets/*")) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stf-mgr-ui.fullname" . }}
  labels:
  {{- include "stf-mgr-ui.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}
