env:
  SPRING_PROFILES_ACTIVE: "perf"
  ENV_NAME: "perf"
  JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m -Xshare:off -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=256m"

ingress:
  enabled: true
  allowedOrigins:
    - wfm-perf.premierinc.com
    - wfm-perf-internal.premierinc.com
    - wfm-perf-east.premierinc.com
    - wfm-perf-eastinside.premierinc.com
  hosts:
    - host: wfm-perf.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-perf-internal.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-perf-east.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-perf-eastinside.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
