env:
  SPRING_PROFILES_ACTIVE: "prod"
  ENV_NAME: "prod"
  JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m -Xshare:off -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=256m"

ingress:
  enabled: true
  allowedOrigins:
    - wfm.premierinc.com
    - wfm-internal.premierinc.com
    - wfm-east.premierinc.com
    - wfm-eastinside.premierinc.com
  hosts:
    - host: wfm.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-internal.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-east.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
    - host: wfm-eastinside.premierinc.com
      paths:
        - path: /pcops/staff-scheduler-ui/
          pathType: Prefix
          port: 8080
