import {OASuggestedData} from '../../domain/OASuggestedData';

export function planDetailsDataService() {
  return [
    {
      name: 'servicetestPlanName',
      key: '12',
      status: 'In Process',
      planCompleted: true,
      action: '',
      corpName: null,
      planUtilizedAvgVol: 5,
      dateUpdated: null,
      departmentCode: null,
      departmentName: null,
      facilityCode: null,
      facilityKey: null,
      facilityName: null,
      censusRange: null,
      userKey: 12,
      deleteFlag: false,
      departmentKey: 589,
      effectiveStartDate: null,
      effectiveEndDate: null,
      temporaryEffectiveStartDate: null,
      temporaryEffectiveEndDate: null,
      targetBudget: 2,
      volume: 1,
      hours: 5,
      workHoursBalance: 44,
      upperEndTarget: 50,
      lowerEndTarget: 100,
      fte: 10,
      userNotes: null,
      utilizedAverageVolume: 1,
      utilizedAverageVolumeBase: 1,
      educationOrientationTargetPaid: 1,
      primaryWHpU: 1,
      secondaryWHpU: 1,
      isnewlycreated: true,
      variableDepartmentPositions: null,
      defaultPlanFlag: true,
      dailyFlag: true,
      offGridActivities: [{
        planId: '1',
        code: '12',
        name: 'serviceactivityName',
        shiftHours: 1,
        typeKey: 2,
        variableDepartmentList: null,
        totalHours: 1,
        key: 1,
      },
      ],
      displayPlanStatus: null,
      corporationId: null,
      staffScheduleList: null,
      nonVariableDepartmentPositions: null,
      totalAnnualVolume: 1,
      totalAnnualHours: 1,
      updatedTimeStamp: null,
      totalAnnualHoursVariance: 1,
      staffingSummaryData: null,
      currentAverageVolume: 1,
      budgetAverageVolume: 1,
      annualizedCurrentAvg: 1,
      annualizedBudgetedAvg: 1,
      planAlreadyInUse : false,
      oAStaffingMetric: null,
    },
    {
      name: 'servicetestPlanName2',
      key: '13',
      status: 'In Process',
      planCompleted: true,
      action: '',
      corpName: null,
      planUtilizedAvgVol: 5,
      utilizedAverageVolume: 6,
      utilizedAverageVolumeBase: 6,
      dateUpdated: null,
      departmentCode: null,
      departmentName: null,
      facilityCode: null,
      facilityKey: null,
      facilityName: null,
      censusRange: null,
      userKey: 13,
      deleteFlag: false,
      departmentKey: 590,
      effectiveStartDate: null,
      effectiveEndDate: null,
      temporaryEffectiveStartDate: null,
      temporaryEffectiveEndDate: null,
      targetBudget: 3,
      volume: 2,
      hours: 6,
      fte: 10,
      educationOrientationTargetPaid: 1,
      primaryWHpU: 1,
      secondaryWHpU: 1,
      workHoursBalance: 45,
      upperEndTarget: null,
      lowerEndTarget: null,
      userNotes: null,
      isnewlycreated: true,
      variableDepartmentPositions: null,
      defaultPlanFlag: true,
      dailyFlag: true,
      offGridActivities: [{
        planId: '2',
        code: '13',
        name: 'serviceactivityName2',
        shiftHours: 2,
        typeKey: 2,
        variableDepartmentList: null,
        totalHours: 2,
        key: 2,
      },
      ],
      displayPlanStatus: null,
      corporationId: null,
      staffScheduleList: null,
      nonVariableDepartmentPositions: null,
      totalAnnualVolume: 1,
      totalAnnualHours: 1,
      updatedTimeStamp: null,
      totalAnnualHoursVariance: 1,
      staffingSummaryData: null,
      currentAverageVolume: 1,
      budgetAverageVolume: 1,
      annualizedCurrentAvg: 1,
      annualizedBudgetedAvg: 1,
      planAlreadyInUse : false,
      oAStaffingMetric: null,
    },

  ];


}
